version: '3.8'

services:
  gemini-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Europe/Moscow
    # Healthcheck для мониторинга состояния контейнера
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Ограничения ресурсов (опционально)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M


